### ISSUE TITLE
F00D service response check

### ISSUE THREAD

**Issue by tomazzz369** [motoharu-gosuto/psvpfstools#12]
today i noticed issue, if we can't get response from f00d service, i disconnect my internet (not on purpose), tool always returns ''header signature is invalid'' and we can't decrypt  content

Successfully decompressed zRIF from provided license string.
Parsing  files.db...
verifying header...
header signature is invalid

of course zrif is proper. that's really confusing, yesterday everything worked, but now doesn't work. what's going on? you should add error if we can't get proper response from f00d

regards

**Comment by motoharu-gosuto** [comment]
Yeah. A good suggestion, thanks. This is a confusing situation that should be fixed.
You are indeed correct. I forgot to add a proper error when there is no response from F00D service.
Also - if you are actively exploring/using the code I suggest you stay with icv-db-support branch for a moment. I am working on support of savedata and trophies at the moment (icv.db format in general).

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
This is fixed now. I am going to make a new release soon. Please check on your side.
