### ISSUE TITLE
Manually enter "Pin/String" for files.db decryption ?

### ISSUE THREAD

**Issue by Gnarmagon** [motoharu-gosuto/psvpfstools#14]
Hey,

I already looked for over an hour into your code but I am really clueless what exactly is needed to open the file.db inside for example the SqlDatabase Browser ?
Are you even doing that or do you go by hex editing ?

Also could you PLEASE add Cross Compile to Cmake or add Binaries to the Releases section ? ( I am sorry but Cmake was the reason I quit C developement so I can't make a PR :( )
I tried yesterday to get it working with VS 2017 CE but I failed because I couldn't get Curl library to work XD

Maybe you could add this to the Readme (very easy Boost lib installation):
`conda install -c conda-forge boost ` (of course you need Conda/Anaconda installed but it is as easy as apt install)

Sorry for this chaotic Issue,

Thanks for all your hard work, I am really envious about what you've done ^^

**Comment by motoharu-gosuto** [comment]
OK - lets try to go through issues one by one.
1. You really stunned me with the first question and I was not able to understand what do you mean at first. db extension has nothing to do with Sql database format. Yes - extension is .db but obviously it is completely different format which is sonys proprietary. Format is based on standard cryptographic primitives though. At some point I am going to describe it on wiki.

**Comment by motoharu-gosuto** [comment]
2. Again I dont understand what do you mean. Cmake is like de facto standard in C world. Many people already confirmed that project can be compiled on Windows and on Linux (Ubuntu) without issues. Which Cross-Compilation do you mean?

**Comment by motoharu-gosuto** [comment]
3. I am not going to add any binaries to Release section at least untill I am done with developement in icv-db-support branch. I see zero reason putting any release binaries there at the moment.
It is trivial enough to compile the project and requires minimal effort if you are on Ubuntu.
I dont know what else I can advise here. If there is something unclear in the readme - feel free to make a PR. If installation is hard on Windows (I can understand that) you always have an option to compile on Linux. Installing all dependencies with apt-get is a piece of cake.

**Comment by motoharu-gosuto** [comment]
4. I see numerous complaints about how hard it is to get boost working. But I really fail to understand that because it is just a matter of executing 2 commands in command line. I guess I will add additional info to readme. Again - if Windows is hard you can always compile on Linux. Installing boost with apt-get is like one command.

**Comment by motoharu-gosuto** [comment]
5. I see no reason dragging conda into the process just because you need boost. If you want you can create a recipe for this project. Feel free to make a PR.
