### ISSUE TITLE
DLC support ?

### ISSUE THREAD

**Issue by leogouttefarde** [motoharu-gosuto/psvpfstools#2]
Hi thanks for your work. Just wondering, would it be possible to support DLC decryption maybe ?

**Comment by motoharu-gosuto** [comment]
Hi. I think these should be already decryptable.
I am still in the process of testing and fixing the tool.
Please let me know if you have any specific issues.

**Comment by leogouttefarde** [comment]
Okay understood, I will start testing. Thanks.

**Comment by leogouttefarde** [comment]
Wow DLC decryption indeed works ! We can extract 3.61+ DLC contents now. Nice !

**Comment by jack980517** [comment]
Not sure if I should comment on a closed issue, but I'm not sure how to decrypt DLC. Here's the output of my failed attempt: 
[output.txt](https://github.com/motoharu-gosuto/psvpfstools/files/2236323/output.txt)

**Comment by TheRadziu** [comment]
@jack980517 
the first line in your output might tell you what the issue is: `Missing option --klicensee or --zRIF` which might be the reason why it throws out so many errors.
