### ISSUE TITLE
Issue Running Application

### ISSUE THREAD

**Issue by mkorsak** [motoharu-gosuto/psvpfstools#20]
I'm trying to decrypt the files I have for a game locally, for Digimon Story Hacker's Memory. I have all of the files that were taken from a pkg file of it. I have the folder structure: C:\Vita\PCSE01171\app\PCSE01171 This then leads to the folders like resources, sce_modules, etc...

I have a zRIF string too for the game. Many times when trying to run it, I had gotten "Root directory does not exist" when trying to run it. Now when moving the game to where it is now and running it with the arguments "psvpfsparser.exe -i C:\Vita\PCSE01171 -o C:\Users\Mark\Downloads\Vita Hacking\output\decrypted -z KO5ifR1dQ+eHBoBcAjHV0NDcEGS/S7CHo7O3a1Cwr6uvf1CkIT7/xdjKl0+ov+DRXMu9qKvb58ZojA9uAAC7LxRO -f http://cma.henkaku.xyz/", I'm getting the error "failed to find unicv.db file or icv.db folder"

Any idea what I'm doing wrong in running this?

**Comment by motoharu-gosuto** [comment]
@mkorsak 
This is very unlikely that you can not use spaces in the path. But I will test it.

**Comment by tomazzz369** [comment]
you error is related with non proper windows command usage, not with psvpfsparser

**Comment by SilicaAndPina** [comment]
you acturally can use spaces. you just have to put the path in Quotes.

--title_id_src="C:\Example Folder\whatever\PCSE001242"

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
Thanks for testing. I assume this issue can be closed.
