### ISSUE TITLE
Directory PCSE00950/data/sce_sys does not exist

### ISSUE THREAD

**Issue by Luro02** [motoharu-gosuto/psvpfstools#22]
I checked it multiple times, and I am sure that the Path including the folder exist (full path:
PCSE00950\data\sce_sys\trophy\NPWR11820_00)

`psvpfsparser -f cma.henkaku.xyz -i PCSE00950 -o PCSE00950_dec -k 58297736930E4F6110630E72C566CA6F`

Console output:
https://ghostbin.com/paste/h95ye
or
[log.txt](https://github.com/motoharu-gosuto/psvpfstools/files/1724575/log.txt)

[PKG_link](http://zeus.dl.playstation.net/cdn/UP1023/PCSE00950_00/UP1023-PCSE00950_00-SHANTAEHALFGENIE_bg_1_2f55334726aab28567d9deeb845fe5540c021924.pkg)

**Comment by tomazzz369** [comment]
weird, but i can confirm, i have the same issue

Klicensee: 58297736930E4F6110630E72C566CA6F
Parsing files.db...
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
13 - OK : ef2c89bf0cb17f3322bd8028c3376add29d93c44
.2 - OK : 6da21b31d65c4adf444f3d70090c0c694e442e77
..0 - OK : 90b0de2f4459a9fea8536cb0032ab867416d65a0

...

..4a - OK : 6f65aa5086d193e35c8f161a842941ff438eab57
..4c - OK : 6b1153c14c2c5b6482c73a573685a0396a6a6a18
..4d - OK : f80bb4a43e1e723818b1f214bd8d3b9145b1a9ef
Hash tree is ok
Building directory matrix...
Building file matrix...
[EMPTY] File xseed index 461 of type 1
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Directory PCSE00950/data/sce_sys does not exist

directory 'PCSE00950/data/sce_sys' of course exists

older version working fine

Klicensee: 58297736930E4F6110630E72C566CA6F
Parsing files.db...
key: 58297736930e4f6110630e72c566ca6f
drv_key: d6dcc7d5be0dece9153369f5d8ad0be0
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
13 - OK : ef2c89bf0cb17f3322bd8028c3376add29d93c44
.2 - OK : 6da21b31d65c4adf444f3d70090c0c694e442e77
..0 - OK : 90b0de2f4459a9fea8536cb0032ab867416d65a0

...

Decrypted: PCSE00950/data/ui_game.pak
Decrypted: PCSE00950/data/ui_hub.pak
Decrypted: PCSE00950/data/vo.fsb
Decrypted: PCSE00950/data/wf_logo.mp4
Decrypted: PCSE00950/data/win_screens.pak

**Comment by motoharu-gosuto** [comment]
Thanks for reporting @Gnarmagon  and thanks for checking @tomazzz369 
I guess this is one of these weird issues. I will try to check what is wrong.

**Comment by tomazzz369** [comment]
another update 1.02 PCSB00583 with the same error:

Klicensee: 05BC4090290E7E8A76F0036A61AF4D85
Parsing files.db...
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
0 - OK : 2448993399cc1bd8d4e622d9aed64830657ae462
1 - OK : a6e39493699afcbf4420531b35276b4f1130ef4b
3 - OK : 9f88b1a69106857ae3bdccebcf963747b103747f
4 - OK : 23596f7c1f60f6d529f3bf7ff94c9babd20f80c9
5 - OK : 1523cba5b7af38d0b87967ce05e2469b68cdc34b
6 - OK : ac9bc695e4d47652008a9065fa197916a08fa120
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Directory EP0745-PCSB00583_00-PBBG0APPLICATION/dlc_furau_pack/sce_sys does not exist

**Comment by motoharu-gosuto** [comment]
fixed in 96d2637fedabe45e06f916e49b574d0bee646c7c

**Comment by motoharu-gosuto** [comment]
@tomazzz369
If you have time - we need to doublecheck that after release.
