### ISSUE TITLE
Incorrect file name, replaces with decrypted folder path

### ISSUE THREAD

**Issue by dots-tb** [motoharu-gosuto/psvpfstools#27]
If a file contained within encrypted content folder has the same name as encrypted folder itself, it will be renamed to the destination folder.

Ex (in "EncFolderName", out "EncFolderName_decrypted"):
EncFolderName 
-> EncFolderName.file

Will become:
EncFolderName_decrypted
 -> EncFolderName_decrypted.file

**Comment by tomazzz369** [comment]
tested and i have the same issue

root dir in: sce_sys // dir in structure: sce_sys/sce_sys/param.sfo
root dir out: sce_sys_decrypted

result: sce_sys_decrypted/sce_sys_decrypted/param.sfo
should be: sce_sys_decrypted/sce_sys/param.sfo

---

Klicensee: 82534E232503CBFE34CA510BA58B7502
Parsing files.db...
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
Parsing unicv.db...
Total blocks: 11
Building unicv.db -> files.db relation...
Match found: 2 sce_sys/sce_sys/param.sfo
Match found: 4 sce_sys/sce_sys/clearsign
Match found: 6 sce_sys/sce_sys/keystone
Match found: 8 sce_sys/dlcPack.dat
Match found: a sce_sys/dlcPack.hed
Creating directories...
Created: sce_sys/sce_sys
Creating empty files...
Decrypting files...
Copied: sce_sys/sce_sys/param.sfo
Copied: sce_sys/sce_sys/clearsign
Decrypted: sce_sys/sce_sys/keystone
Decrypted: sce_sys/dlcPack.dat
Decrypted: sce_sys/dlcPack.hed
Keystone sanity check...
Keystone does not exist

**Comment by tomazzz369** [comment]
tested older versions v2 and v1, same issue

root dir in: resource // dir in structure: resource/resource/common_resource.rco
root dir out: resource_decrypted

same with file name, but only if file name contain dir name (common_resource.rco)

result: resource_decrypted/resource_decrypted/common_resource_decrypted.rco
should be: resource_decrypted/resource/common_resource.rco

file names that doesn't contains dir name are fine

resource_decrypted/resource_decrypted/system_plugin.rco
resource_decrypted/resource_decrypted/twitter_plugin.rco

**Comment by motoharu-gosuto** [comment]
fixed in 96d2637fedabe45e06f916e49b574d0bee646c7c

**Comment by motoharu-gosuto** [comment]
@tomazzz369
If you have time - we need to doublecheck that after release.
