### ISSUE TITLE
.bat won't launch

### ISSUE THREAD

**Issue by CloudZayne** [motoharu-gosuto/psvpfstools#34]
I can't launch the .bat for an unknown (to me) reason. I tried to launch it through powershell and this was the contents:

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set BOOST_INCLUDEDIR=N:\svnroot\src\vendor\boost_1_55_0

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set BOOST_LIBRARYDIR=N:\svnroot\vendor\boost_1_55_0\vc110\lib

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set CURL_INCLUDE_DIR=C:\Program Files (x86)\curl_win7\include

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set CURL_LIBRARY=C:\Program Files (x86)\curl_win7\lib\libcurl-d_imp.lib

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set ZLIB_INCLUDE_DIR=N:\zlib

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set ZLIB_LIBRARY=N:\zlib\contrib\vstudio\vc11\x86\ZlibStatDebug\zlibstat.lib

C:\Users\tasty\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set LIBTOMCRYPT_INCLUDE_DIR=N:\libtomcrypt\build\include

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>set LIBTOMCRYPT_LIBRARY=N:\libtomcrypt\build\lib\tomcrypt.lib

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>rmdir build /S /Q

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>mkdir build

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake>cd build

C:\Users\..\Desktop\PsVita\Decrypter\psvpfstools-master\cmake\build>cmake ../ -G "Visual Studio 11 2012"
'cmake' is not recognized as an internal or external command,
operable program or batch file.

**Comment by motoharu-gosuto** [comment]
@CloudZayne 
Hi. Are you trying to build psvpfstools?
In this case please read the readme.
You have to install cmake prior to building the project.
This error indicates that you do not have cmake installed:
'cmake' is not recognized as an internal or external command,

**Comment by CloudZayne** [comment]
Oh, okay thank you!

Edit:
I installed cmake, and i'm getting this error when i try to generate it
"error in configuration process, project files may be invalid"
and this is in the output log
"The system is: Windows - 10.0.17134 - AMD64"
I don't understand that because I don't have any AMD hardware in my pc.

**Comment by motoharu-gosuto** [comment]
@CloudZayne 
Do you have Visual Studio installed?
If No - you need to install it.
If Yes - which version? Is it different from 2012?
If No - please shared output of `cmake --help` command
If Yes - you need to adjust .bat to select different -G (generator) option to suit your Visual Studio version.
