### ISSUE TITLE
We can decrypt F00D now.. so.. is f00d service really still needed?

### ISSUE THREAD

**Issue by LiEnby** [motoharu-gosuto/psvpfstools#36]
Was wondering if you could make it get the encrypted keys locally since we can decrypt f00d now using team molecule's SceUtils.

**Comment by tomazzz369** [comment]
+1

**Comment by motoharu-gosuto** [comment]
@KuromeSan, @tomazzz369
I am already working on this. It requires some amount of reversing so it takes some time.
<https://github.com/motoharu-gosuto/psvcmd56/blob/master/src/CMD56Reversed/F00D/KprxAuthService.cpp>
The only thing left is to integrate this into the tool.

**Comment by motoharu-gosuto** [comment]
implemented in 1312f3dfdeee27a7335a04a5713f5787bbbd6521
