### ISSUE TITLE
ERROR: Unable to get response from F00D  service

### ISSUE THREAD

**Issue by HyemiChan** [motoharu-gosuto/psvpfstools#37]
Hello! 
This is my first time using this tool.. I keep on searching the web on how to use this.. i encountered this error.. i cant find a better explanation on how to solve this error: Unable to get response from F00D services
(after reading some things here, i'm still quite confuse) 
How can i fix this error? It will be a huge help! Thanks!

**Comment by CelesteBlue-dev** [comment]
-f cma.henkaku.xyz

**Comment by motoharu-gosuto** [comment]
@HyemiChan
You have to provide a link to the service as Celeste mentioned.
But anyway - I will soon get rid of the service requirement.
