### ISSUE TITLE
Cannot decrypt trophy data files

### ISSUE THREAD

**Issue by SilicaAndPina** [motoharu-gosuto/psvpfstools#4]
i tried doing
     $ ./psvpfsparser --title_id_src=NPWR07969_00 --title_id_dst=output --zRIF=KO5ifR1dQ+eHBhgZWFhCTTW1MILYH+bqFxIa5Bri6esa4OiNz38BmwQrHjwosS3kSJ/G8iWuYTTGBzcAAB/wFIIA --f00d_url=cma.henkaku.xyz

and received this output:
    Successfully decompressed zRIF from provided license string.
    Parsing  files.db...
    verifying header...
    header signature is invalid

please fix trophy data >_>

**Comment by motoharu-gosuto** [comment]
Did you read the readme?
I think it clearly explains what you should pass as --title_id_src
-i [ --title_id_src ] arg Source directory that contains the application. Like PCSC00000.

It does not look to me that NPWR07969_00 is a root application folder that contains:
sce_pfs/files.db
sce_pfs/unicv.db

**Comment by SilicaAndPina** [comment]
how would you get the trophy data to decrypt then? there acturally is a sce_pfs with files.db and univ.db/ inside the games trophy data folder (NPWR07969_00) if i did the games actural application folder then it wouldnt decrypt the trophy data which is what im trying to do..

**Comment by motoharu-gosuto** [comment]
Dude, whats your problem? I told you already that your arguments are wrong.
Source directory must not be a tropy directory.
How did it happen that files.db and univ.db are inside tropy directory?

Here is a working example where I decrypt "Adventure Time: The Secret of the Nameless Kingdom".
I guess thats where NPWR07969_00 is coming from.

Before decryption I specifically went to  trophy directory and examined that "PCSE00582_00-ADVENTURETIMEPAK\sce_sys\trophy\NPWR07969_00\TROPHY.TRP" file contains random crap.

Then I execute this command:
psvpfsparser.exe --title_id_src "I:\PS Vita Games\Adventure Time The Secret of the Nameless Kingdom\PCSE00582_00-ADVENTURETIMEPAK" --title_id_dst "I:\PS Vita Games\Adventure Time The Secret of the Nameless Kingdom\PCSE00582_00-ADVENTURETIMEPAK_dec" --zRIF "KO5ifR1dQ+eHBhgZWFhCTTW1MILYH+bqFxIa5Bri6esa4OiNz38BmwQrHjwosS3kSJ/G8iWuYTTGBzcAAB/wFIIA" --f00d_url http://cma.henkaku.xyz

I get a log that contains these lines:
Match found: 61 I:/PS Vita Games/Adventure Time The Secret of the Nameless Kingdom/PCSE00582_00-ADVENTURETIMEPAK/sce_sys/trophy/NPWR07969_00/TROPHY.TRP

Created: I:/PS Vita Games/Adventure Time The Secret of the Nameless Kingdom/PCSE00582_00-ADVENTURETIMEPAK/sce_sys/trophy

Created: I:/PS Vita Games/Adventure Time The Secret of the Nameless Kingdom/PCSE00582_00-ADVENTURETIMEPAK/sce_sys/trophy/NPWR07969_00

Decrypted: I:/PS Vita Games/Adventure Time The Secret of the Nameless Kingdom/PCSE00582_00-ADVENTURETIMEPAK/sce_sys/trophy/NPWR07969_00/TROPHY.TRP

Log messages sure are not enough. So I went to the tropy directory and examined the TROPHY.TRP file again. Obviously it does not contain random crap anymore. Instead I clearly see the data and strings like TROPCONF.SFM, TROP.SFM, ICON0.PNG etc.

**Comment by SilicaAndPina** [comment]
thats the trophy SET not the trophy DATA,
the trophy SET is located at app0:sce_sys/trophy the trophy DATA (that acturally stores what trophys are unlocked and such) is PFS encrypted and stored at ur0:user/00/trophy/data/NPWR07969_00 and contains the files TRPTRANS.DAT and TRPTITLE.DAT along with a sce_pfs folder containing the files.db and univ.db 
feel free to look at ur0:user/00/trophy/data yourself youll see what i mean.

**Comment by motoharu-gosuto** [comment]
Ok. Now I see what you mean. However there is a problem.
I can extend the parser, but it does not look like zRIF string that you use for the game can be used to decrypt trophy data from ur0. Technically only thing I need from zRIF string is klicensee.
I have tried with Gravity Rush. There are 3 scenarios for deriving the keys from klicensee. 
These keys are required to check some signatures, hashes, match the files and also do decryption.
None of 3 scenarios worked for checking the header signature of files.db. This is the same error as you get: header signature is invalid.

**Comment by SilicaAndPina** [comment]
does savedata work? its probably the same as that if it is, since both are meant to be decrypted & encrypted again.

**Comment by motoharu-gosuto** [comment]
Is savedata located at ur0:user/00/savedata?
I dont see any pfs encrypted files there.

**Comment by SilicaAndPina** [comment]
its ux0:user/00/savedata

**Comment by motoharu-gosuto** [comment]
I have checked the savedata. It looks like zRIF string from game (or strictly speaking klicensee)
can not be applied to savedata decryption as well.
I may try to look into it but I dont promise anything.
If you could do RE on your own to confirm that klicensee IS used or IS NOT used (some other key in this case) this will be great.

**Comment by CelesteBlue-dev** [comment]
I am sure that : 
- savedata can be decrypted without having the game, SO klicensee has no link with savedata encryption/decryption
- savedata embeds in decrypted form the PSN account_id ( or local account_id if not connected with a PSN account)
 ----> SO maybe PFS savedata decryption uses the account_id
BUT I think it doe not.
- I remarked that editing pfsSkKey file before encryption gives a DIFFERENT encryption result
AND that editing pfsSkKey file before decryption PREVENTS decryption.

So, I think that the key used is in the pfsSkKey file and that this is the only needed key to decrypt savedata.

**Comment by motoharu-gosuto** [comment]
You are talking about sealedkey, right? I was actually thinking too that sealedkey or keystone could be involved.

**Comment by CelesteBlue-dev** [comment]
Yes I'm talking about the sealedkey file.
https://twitter.com/CelesteBlue123/status/929812686900219905
I've began reversing PS4 functions : 
SealedKey is the PFS local key for savedata / trophies enc/dec.
_sceSblSsSealedKeyIoctl -> sceSblSs[Decrypt/Generate]SealedKey -> sub ("getSealedKeySecret") -> sceSblSsDecryptWithPortability
Now I see : "pfsSKKey__SecKey" !

**Comment by motoharu-gosuto** [comment]
sealedkey indeed turned out to be the key for savedata. did not check the trophy yet.
header checks in files.db now pass. you can check latest commits.
There are other changes in files.db parser. And I still need time to implement icv.db folder parser.
Did not commit this part yet.

**Comment by SilicaAndPina** [comment]
trophys do not work, now gives
sealedkey will be used
using sealedkey...
sealedkey: matched retail hmac
parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Unexpected file type

**Comment by motoharu-gosuto** [comment]
Well. As I said - I did not implement everything yet. 
However please notice in the log that now sealedkey is used and signature checks now pass.
Meaning that we know what is the key for tropy/savedata.

**Comment by SilicaAndPina** [comment]
Awesome, how bout re-encrypting the savedata / trophy data after?

**Comment by CelesteBlue-dev** [comment]
It will be possible but encryption will be harder to reverse and so I would advice you to decrypt on PC but encrypt on PSVita (I'll add NIDs and code to wiki).

**Comment by SilicaAndPina** [comment]
oh also with the new code nothing gets decrypted at all, even what used to work doesnt anymore.

**Comment by motoharu-gosuto** [comment]
Yeah sorry this is my mistake. I will fix it today probably. I am still struggling with decryption =(. 
Looks like algorithms are not exactly the same for savedata and trophy. So I will probably have to do more reversing.
If you want hot fix: find all calls to scePfsUtilGetSecret and pass FILES_GAME_TYPE instead of flag.
This should do the trick I think.

**Comment by ShumnoT** [comment]
Any progress?

**Comment by motoharu-gosuto** [comment]
I am planning to continue next week. I am busy right now.
I already have a parser for icv.db (which is a bit different from unicv.db).
This format is used for saves and trophies.
I guess this part of code will go to separate branch first.
I was able to verify the hash tree that is stored in files.db
However it is not yet clear how to decrypt the files. Looks like there are some differences in process, compared to game or dlc decryption.

**Comment by SilicaAndPina** [comment]
cant seem to compile it.
getting 
/home/silicaandpina/psvita/GIT/psvpfstools/psvpfsparser/PfsDecryptor.cpp: In function ‘int decrypt_files(boost::filesystem::path, boost::filesystem::path, unsigned char*, sce_ng_pfs_header_t&, std::vector<sce_ng_pfs_file_t>&, std::vector<sce_ng_pfs_dir_t>&, scei_rodb_t&, std::map<unsigned int, std::__cxx11::basic_string<char> >&, std::set<std::__cxx11::basic_string<char> >&)’:
/home/silicaandpina/psvita/GIT/psvpfstools/psvpfsparser/PfsDecryptor.cpp:560:22: error: ‘class scei_rodb_t’ has no member named ‘tables’
    for(auto& t : fdb.tables)
                      ^
/home/silicaandpina/psvita/GIT/psvpfstools/psvpfsparser/PfsDecryptor.cpp:584:34: error: ‘directory’ is not a member of ‘sce_ng_pfs_file_types’
       if(file->file.info.type == sce_ng_pfs_file_types::directory ||

**Comment by motoharu-gosuto** [comment]
Well. Thats because I did not commit all the changes to the icv-db-support branch yet.
There are quite a lot of them so I am trying to go carefully, slowly checking all the code in the parsers. 
Not to break the logic etc.

**Comment by tomazzz369** [comment]
small question, --f00d_url http://cma.henkaku.xyz is not needed for verifying header? for example if i only want to check if zrif/klicense is valid. regards

**Comment by motoharu-gosuto** [comment]
What header do you mean exactly? If you want to verify files.db header:
https://github.com/motoharu-gosuto/psvpfstools/blob/icv-db-support/psvpfsparser/FilesDbParser.cpp#L31
you will need F00D. This is because header contains couple of hmac values and to calculate them you need to derive a secret from klicensee if you are decrypting game. Or from key in sealedkey file if you are decrypting smth like save data.
If you want to verify unicv.db header:
https://github.com/motoharu-gosuto/psvpfstools/blob/icv-db-support/psvpfsparser/UnicvDbTypes.cpp#L7
you dont need F00D.

Also, what is your condition for klicensee/zrif to be valid? Data is not broken? Like when base64 string contains correct data. Or that klicensee matches the game?

**Comment by tomazzz369** [comment]
i noticed if zrif/klicense is invalid, header signature is invalid

https://github.com/motoharu-gosuto/psvpfstools/blob/icv-db-support/psvpfsparser/FilesDbParser.cpp#L49

if zrif/klicense is fine header signature is valid

https://github.com/motoharu-gosuto/psvpfstools/blob/icv-db-support/psvpfsparser/FilesDbParser.cpp#L53

regards

**Comment by motoharu-gosuto** [comment]
Yes. Exactly what I am talking about then.
To validate the signature in files.db you need to get a "secret" first.
This is derived from klicensee here:
https://github.com/motoharu-gosuto/psvpfstools/blob/icv-db-support/psvpfsparser/FilesDbParser.cpp#L108
You need F00D to perform this operation.

**Comment by tomazzz369** [comment]
thanks for answer

regards

**Comment by SilicaAndPina** [comment]
is this function working yet?

**Comment by motoharu-gosuto** [comment]
@SilicaAndPina 
Everything is now working. I am going to prepare a binary release this weekend.
Please check on your side - master branch.

**Comment by tomazzz369** [comment]
please compile with win xp 32 bit support

regards

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
I might try, not sure. Will you help me testing this build?

**Comment by tomazzz369** [comment]
off course. i'm asking because i have installed win xp on my desktop pc and i use it for 90% of the time

regards

**Comment by SilicaAndPina** [comment]
I can compile windows I managed to do it before. . .

**Comment by tomazzz369** [comment]
i have your version and not working on win xp 32 bit only on win 7

**Comment by SilicaAndPina** [comment]
Why windows xp ...

**Comment by tomazzz369** [comment]
because i don't see a reason for update my system, since everything what i need works fine on win xp

**Comment by SilicaAndPina** [comment]
Hm well does winXP run visual C 2011 ?

**Comment by tomazzz369** [comment]
i have compiled older commit with visual studio 2012 and working fine

**Comment by motoharu-gosuto** [comment]
@SilicaAndPina 
You are talking about windows build like it is some black magic.
It is not a big issue to compile for XP. You need additional platform toolset.
Dont worry - I have everything configured for both Windows and Ubuntu.
I will build it myself.

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
Closing this issue.
Discussion about builds moves to:
https://github.com/motoharu-gosuto/psvpfstools/issues/17
