### ISSUE TITLE
Help decrypt assets

### ISSUE THREAD

**Issue by MadTooth** [motoharu-gosuto/psvpfstools#49]
I can’t decrypt asset files from the game PCSG01179	JP	Catherine: Full Body (3.61+!) [3.69]

http://zeus.dl.playstation.net/cdn/JP0005/PCSG01179_00/JP0005-PCSG01179_00-ZZZZZZZZZZZZZZZZ_bg_1_5bab26208abd25132ea925bb4dd87def61265134.pkg
KO5ifR1dQ+d7BYCshdhiaGhuCbI/Cg3g89+/2O0Rr/hPlNcszFq38XgML4XBxTiaYmgLAAhcFsYA	JP0005-PCSG01179_00-ZZZZZZZZZZZZZZZZ
2019-02-13 15:02:44	キャサリン・フルボディ	3134556608	5bcff88e2f40008980271fded8eace750538b05f598d4ccbfb8565197a56319b	3.69

You can make a video how to decrypt assets ?
![image](https://user-images.githubusercontent.com/30464341/72152112-a27acd00-33dc-11ea-8141-eca221a0b3af.png)

**Comment by ghost** [comment]
-f cma.henkaku.xyz

**Comment by MadTooth** [comment]
It does not work for me
d9f1a96463458673: ef57f6ea63b154deeb2434b37341ed6fe2e11a17a42e92472986e181453f077e
![image](https://user-images.githubusercontent.com/30464341/72163609-b9c6b400-33f6-11ea-88f3-5b4b7baa53d0.png)
![image](https://user-images.githubusercontent.com/30464341/72164163-c26bba00-33f7-11ea-96c3-5a6770387618.png)

![image](https://user-images.githubusercontent.com/30464341/72164067-9a7c5680-33f7-11ea-911e-90b78bd80d89.png)

**Comment by ghost** [comment]
-f [URL]
psvpsfparser -i PCSG01179 -o PCSG01179_dec -z KO5ifR1dQ+d7BYCshdhiaGhuCbI/Cg3g89+/2O0Rr/hPlNcszFq38XgML4XBxTiaYmgLAAhcFsYA  -f cma.henkaku.xyz

**Comment by MadTooth** [comment]
It works now
psvpfsparser.exe -i in -o out -z KO5ifR1dQ+d7BYCshdhiaGhuCbI/Cg3g89+/2O0Rr/hPlNcszFq38XgML4XBxTiaYmgLAAhcFsYA -f cma.henkaku.xyz
![image](https://user-images.githubusercontent.com/30464341/72920607-37d27580-3d7c-11ea-9e77-79c5924ad44d.png)
