### ISSUE TITLE
"Invalid version" message received when decrypting Atelier Totori Plus

### ISSUE THREAD

**Issue by SilicaAndPina** [motoharu-gosuto/psvpfstools#5]
$ ./psvpfsparser --title_id_src=PCSE00231 --title_id_dst=PCSE00231_dec --zRIF=KO5ifR1dQ+eHBpgYGlhATTUyNgTbHxBggAzw+S/+2USeH1tDE18sOmzay5NqMhrjgxsAAJ5LE7xl --f00d_url=cma.henkaku.xyz
gives me:
Successfully decompressed zRIF from provided license string.
Parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Invalid version

**Comment by motoharu-gosuto** [comment]
Nice. Good that you have found another version.
I will check this.

**Comment by motoharu-gosuto** [comment]
This should be fixed now. Version 4 of files.db is now handled properly. Also enabled one of the scenarios for key derivation.

**Comment by SilicaAndPina** [comment]
now it wont compile on windows at all
after running build.bat i get a "The operation could not be completed, Unspecified Error" in visual studio 2011 

and i JUST got it working in windows too.. >_>

**Comment by motoharu-gosuto** [comment]
System.Collections - is this something from C# ?
I have no idea where it is coming from. I doubt this error is related to psvpfstools.

**Comment by SilicaAndPina** [comment]
well it happened when i tried to build the project created by psvpfstools.
but its probably my fault like i said before..

**Comment by SilicaAndPina** [comment]
yep. the problem was with Visual Stuido itself (some shit in the cache files) cleared them out and it works fine.
