### ISSUE TITLE
Error with game 3.61+

### ISSUE THREAD

**Issue by chronoss09** [motoharu-gosuto/psvpfstools#8]
I want to decrypt the with the new version of Psvimgtools-Easy-FrontEnd and i have this error

<a href="https://gyazo.com/38d64c1a9ec9fb661c2b4c9f791dbd5d"><img src="https://i.gyazo.com/38d64c1a9ec9fb661c2b4c9f791dbd5d.png" alt="https://gyazo.com/38d64c1a9ec9fb661c2b4c9f791dbd5d" width="479"/></a>

It means, it's not possible now to decrypt 3.61+ game or just an error ?

**Comment by tomazzz369** [comment]
Shantae: Half-Genie Hero 3.61+ app and update working fine with psvpfstools compiled by SilicaAndPina

https://drive.google.com/file/d/1WD1mTXxykoWkPPPMiX0AkYMUtEc6mSwC/view

btw why you add error in psvpfstools instead in Psvimgtools-Easy-FrontEnd?

**Comment by chronoss09** [comment]
Thanks for the tips !

Error is for PFS decrypt and PFS is for psvpfstools,  i think you understand me...

**Comment by motoharu-gosuto** [comment]
I will be closing this issue, because:
1. No title id is provided, so that I can not test decryption of that title.
2. No clear explanation of error is provided. I see the screenshot, however this is a generic error that is coming from Psvimgtools-Easy-FrontEnd. It tells nothing about what happened in psvpfstoos.

**Comment by chronoss09** [comment]
The title ID of the game is : PCSE00965

**Comment by tomazzz369** [comment]
everything working fine for me:

Successfully decompressed zRIF from provided license string.
Parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Validating hash tree...
0 - OK : 58eafdfdac40d6c89234e43eeca12f649ba3fd4b
1 - OK : 1fe8fd0bc4c763390a9373f34da11f18988754c9
3 - OK : 956dfa64b2bc29b66936f1908c9a436f7fefd47b
4 - OK : 89f7c9cd89bc91321968b8d271a2eb2f12462f21
5 - OK : eceb6fb6b1291e5d0b9a385495176963619b0bcd
6 - OK : d1e13ad2f537939ffbd49a4d4812e2a75e5789b8
7 - OK : cfeef7f4c8173378f54b5447c126481f111f2094
8 - OK : 1aba2211e360547aba788e240525fee09e0902cc
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Validating dir paths...
Validating file paths...
Matching file paths...
Parsing  unicv.db...
Total blocks: 122
Building unicv.db -> files.db relation...
Match found: 8 PCSE00965/sce_sys/param.sfo
Match found: 10 PCSE00965/sce_sys/about/right.suprx
Match found: 12 PCSE00965/sce_sys/clearsign
Match found: 14 PCSE00965/sce_sys/icon0.png
Match found: 16 PCSE00965/sce_sys/keystone
Match found: 18 PCSE00965/sce_sys/livearea/contents/background.png
Match found: 20 PCSE00965/sce_sys/livearea/contents/gate.png
Match found: 22 PCSE00965/sce_sys/livearea/contents/template.xml
Match found: 24 PCSE00965/sce_sys/manual/001.png
Match found: 26 PCSE00965/sce_sys/manual/002.png
Match found: 28 PCSE00965/sce_sys/manual/003.png
Match found: 30 PCSE00965/sce_sys/nptitle.dat
Match found: 32 PCSE00965/sce_sys/pic0.png
Match found: 34 PCSE00965/sce_sys/trophy/NPWR12057_00/TROPHY.TRP
Match found: 37 PCSE00965/sce_module/libc.suprx
Match found: 39 PCSE00965/sce_module/libfios2.suprx
Match found: 41 PCSE00965/sce_module/libult.suprx
Match found: 43 PCSE00965/eboot.bin
Match found: 48 PCSE00965/1a9c33dcd0301dfd
Match found: 50 PCSE00965/1c18b562b8fc6781
Match found: 52 PCSE00965/44bcc04093e5c506
Match found: 54 PCSE00965/47f1b7369bdf82c5
Match found: 56 PCSE00965/8cbde06d754ef613
Match found: 58 PCSE00965/96438abc757b9f23
Match found: 60 PCSE00965/9ba626afa44a3aa3
Match found: 105 PCSE00965/ac5c2f0670e5d674
Match found: 107 PCSE00965/b4d3a1fda591b2a4
Match found: 109 PCSE00965/bundle_database.data
Match found: 111 PCSE00965/c766ddd8a6875c02
Match found: 113 PCSE00965/da7fcae0c6c80345
Match found: 115 PCSE00965/f0983aed14ed1f8f
Match found: 117 PCSE00965/images/psvita_icon.png
Match found: 119 PCSE00965/settings.ini
Match found: 121 PCSE00965/test.ini
Creating directories...
Created: PCSE00965/sce_sys
Created: PCSE00965/sce_sys/about
Created: PCSE00965/sce_sys/livearea
Created: PCSE00965/sce_sys/livearea/contents
Created: PCSE00965/sce_sys/manual
Created: PCSE00965/sce_sys/trophy
Created: PCSE00965/sce_sys/trophy/NPWR12057_00
Created: PCSE00965/sce_module
Created: PCSE00965/dlc
Created: PCSE00965/images
Creating empty files...
Decrypting files...
Copied: PCSE00965/sce_sys/param.sfo
Decrypted: PCSE00965/sce_sys/about/right.suprx
Copied: PCSE00965/sce_sys/clearsign
Decrypted: PCSE00965/sce_sys/icon0.png
Decrypted: PCSE00965/sce_sys/keystone
Decrypted: PCSE00965/sce_sys/livearea/contents/background.png
Decrypted: PCSE00965/sce_sys/livearea/contents/gate.png
Decrypted: PCSE00965/sce_sys/livearea/contents/template.xml
Decrypted: PCSE00965/sce_sys/manual/001.png
Decrypted: PCSE00965/sce_sys/manual/002.png
Decrypted: PCSE00965/sce_sys/manual/003.png
Decrypted: PCSE00965/sce_sys/nptitle.dat
Decrypted: PCSE00965/sce_sys/pic0.png
Decrypted: PCSE00965/sce_sys/trophy/NPWR12057_00/TROPHY.TRP
Decrypted: PCSE00965/sce_module/libc.suprx
Decrypted: PCSE00965/sce_module/libfios2.suprx
Decrypted: PCSE00965/sce_module/libult.suprx
Decrypted: PCSE00965/eboot.bin
Decrypted: PCSE00965/1a9c33dcd0301dfd
Decrypted: PCSE00965/1c18b562b8fc6781
Decrypted: PCSE00965/44bcc04093e5c506
Decrypted: PCSE00965/47f1b7369bdf82c5
Decrypted: PCSE00965/8cbde06d754ef613
Decrypted: PCSE00965/96438abc757b9f23
Decrypted: PCSE00965/9ba626afa44a3aa3
Decrypted: PCSE00965/ac5c2f0670e5d674
Decrypted: PCSE00965/b4d3a1fda591b2a4
Decrypted: PCSE00965/bundle_database.data
Decrypted: PCSE00965/c766ddd8a6875c02
Decrypted: PCSE00965/da7fcae0c6c80345
Decrypted: PCSE00965/f0983aed14ed1f8f
Decrypted: PCSE00965/images/psvita_icon.png
Decrypted: PCSE00965/settings.ini
Decrypted: PCSE00965/test.ini

**Comment by LamLance289** [comment]
Hi I would like to know how to use this tool please, cause I am new here

**Comment by chronoss09** [comment]
@tomazzz369 : which tool are you using ?

**Comment by tomazzz369** [comment]
psvpfstools

**Comment by chronoss09** [comment]
Yes, i decrypt the game with psvpfstools compiled by SilicaAndPina but how to install it ?

**Comment by TheRadziu** [comment]
You cant. Dont confuse pfs encryption with eboot encryption.

**Comment by chronoss09** [comment]
Ok thanks !

**Comment by motoharu-gosuto** [comment]
Closing this issue since decryption works.
