### ISSUE TITLE
psvpfstools crash

### ISSUE THREAD

**Issue by tomazzz369** [motoharu-gosuto/psvpfstools#9]
psvpfstools crash on dlc

Successfully decompressed zRIF from provided license string.
Parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Validating hash tree...
Hash tree is ok
Building directory matrix...
Building file matrix...
[EMPTY] File online_pass.txt index 9 of type 1
Flattening file pages...
Building dir paths...
Building file paths...
Validating dir paths...
Validating file paths...
Matching file paths...
Parsing  unicv.db...
Total blocks: 9

and crash

zrif:
KO5ifR1dQ+eHBlgi6TKzBNkfEOwY7BTk7+fj6eca4BgcjM9/fAJ2vaJz2/iECnu9nqnn/aEstFg2jKYY2gIA63ET7gAA

pkg link:
http://zeus.dl.playstation.net/cdn/UP9000/PCSA00069_00/MtTCahiagMhJmRLjdeUpZEJuGBKFGfRyFEZMlHIpRlafpuPEcNlnBdgyjxskABCgscARtGgFCvPavUELwxnunORHFcMTJRQzkTWSX.pkg

// removed inactive link

**Comment by motoharu-gosuto** [comment]
Can you check this again in icv-db-support branch?
How did the crash look? Was that an error, an assert window? Segfault?

**Comment by tomazzz369** [comment]
no error on window tool, tool just stops after Total blocks: 9 and new window shows up. application psvpfsparser.exe stopped working

i have this issue only on this one specific dlc:  PlayStation All-Stars Battle Royale Online Pass, i tested same dlc from three regions (PCSF00153, PCSA00069, PCSD00040), on all tool crash

**Comment by motoharu-gosuto** [comment]
Wait a second. I do not understand what window tool are you talking about?
Are you using some frontend for psvpfstools like Psvimgtools-Easy-FrontEnd?
I am most certain that it uses old version of code from master branch.
That is why I suggested checking out icv-db-support branch.

**Comment by tomazzz369** [comment]
yes, tested on older version from master branch. i added this issue 24 days ago

could you share latest compiled version, because i don't have access to my laptop til monday

regards

**Comment by motoharu-gosuto** [comment]
This is not very urgent so it can wait. I dont feel like releasing binaries right now because I want to finish icv support first.

**Comment by tomazzz369** [comment]
v2.0 stops crashing, instead of crash now there is Error: wrong magic

Successfully decompressed zRIF from provided license string.
parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Validating hash tree...
Hash tree is ok
Building directory matrix...
Building file matrix...
[EMPTY] File online_pass.txt index 9 of type 1
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
parsing  unicv.db...
Total blocks: 9
Error: wrong magic

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
Wow. Now THAT is interesting. I will try to find this title and check it out.

**Comment by tomazzz369** [comment]
pkg link and zrif is in first comment

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
I have reproduced the issue. Not sure what to do though.
I dont think that unicv.db file is correct.
Last two pages in this file are completely empty.
I may try to add some code to skip such cases. However this is really weird.

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
Fixed. Please try again.

**Comment by tomazzz369** [comment]
seems to everything is fine

---

question how can i put manually drv_key in F00DKeyEncryptor and skip f00d connection?

i want to read drv_key from file instead from f00d response for offline mode. i want to make something like this: before execute_url, if file f00d.txt exist read drv_key from f00d.txt else execute_url and get drv_key from f00d (as now)

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
lets move discussion to corresponding issue
